---
versions:
  "36.3.8f":
    folder: all
build_types:
  - Release
limit_to_platform_combinations:
  - native-centos7-gcc10-x86_64
  - native-macos11-xcode13-x86_64
  - native-macos12-xcode13-armv8
  - native-win2019-vs2019-x86_64

needs_artifactory_api_key: true
