---
versions:
  "2.11.1":
    folder: all
build_types:
  - Release
needs_artifactory_api_key: true
limit_to_platform_combinations:
  - native-centos7-gcc10-x86_64
  - native-macos10.15-xcode12-x86_64
  - native-macos12-xcode13-armv8
  - native-macos12-xcode13-x86_64
  - native-windows-msvc16-x86_64
require_override:
  - expat/2.4.7@
