---
versions:
  "2.11.1":
    folder: all
build_types:
  - Release
needs_artifactory_api_key: true
limit_to_platform_combinations:
  - native-centos7-gcc10-x86_64
  - native-macos11-xcode13-x86_64
  - native-win2019-vs2019-x86_64
