---
versions:
  - 2.13.93
build_types:
  - Release
macos_brew_preinstall:
  - pkg-config
platform_combinations:
  - build: centos7-gcc10-x86_64
    target: centos7-gcc10-x86_64
  - build: ubuntu20-gcc10-x86_64
    target: ubuntu20-gcc10-x86_64
  - build: macos11-xcode13-x86_64
    target: macos11-xcode13-x86_64
