---
versions:
  - 2.13.93
build_types:
  - Release
macos_brew_preinstall:
  - pkg-config
limit_to_platform_combinations:
  - native-centos7-gcc10-x86_64
  - native-ubuntu20-gcc10-x86_64
  - native-macos11-xcode13-x86_64
  - native-macos12-xcode13-armv8
