---
versions:
  "3.7.0.8":
    folder: all
macos_deployment_target: "10.13"
additional_profiles_for_all_platform_combinations: povray-options
build_types:
  - Release
limit_to_platform_combinations:
  - native-centos7-gcc10-x86_64
  - native-macos11-xcode13-x86_64
  - native-macos12-xcode13-armv8
  - native-win2019-vs2019-x86_64
