---
versions:
  "2.8.117":
    folder: all
build_types:
  - Release
  - Debug
use_release_zlib_profile: true
package_build_alternatives:
  - name: for-gsoap
    additional_target_profiles:
      - gsoap-options