#!/bin/bash -x 

set -e

WS=$(cd $(dirname ${BASH_SOURCE})/../../; pwd)

# needed for qtwebengine
brew install pyenv
eval "$(pyenv init -)"
pyenv install --skip-existing 2.7.18

export PATH=$PATH:$HOME/.pyenv/versions/2.7.18/bin

export LOCAL_CONAN_INDEX=./conan-ccdc-index
export LCI_PLATFORM_COMBINATION="native-macos12-xcode13-armv8"

rm -rf ~/.conan
conan config install $WS/conan-ccdc-common-configuration

conan user --remote ccdc-3rdparty-conan --password=$ARTIFACTORY_API_KEY $USER
conan user --remote ccdc-3rdparty-conan-testing --password=$ARTIFACTORY_API_KEY $USER
conan user --remote public-conan-center --password=$ARTIFACTORY_API_KEY $USER
conan user --remote public-conan-bincrafters --password=$ARTIFACTORY_API_KEY $USER


cit publish recipe
cit build
